[Command1]
group = "Predefined"
description = "Simple command description1"
command = "kubectl get pods -A --field-selector=status.phase!=Running | grep -v Complete"

[Command2]
group = "Predefined2"
description = "Simple command description2"
command = "kubectl get pods -A --field-selector = status.phase = Running | grep -v Complete"

[Command3]
group = "Predefined3"
description = "Simple command description3"
command = """ kubectl get no -o json | \
              jq -r '.items | sort_by(.status.capacity.memory)[]|[.metadata.name,.status.capacity.memory]| @tsv' """

[Command4]
group = "Predefined4"
description = "Simple command description4"
command = """ kubectl get pods -A --field-selector = status.phase! = Running\
              | grep -v Complete \
              | grep -v Complete \
              | grep -v Complete \
              | grep -v Complete """

[Command5]
group = "Predefined5"
description = "Simple command description5"
command = "kubectl get pods -A --field-selector=status.phase!=Running | grep -v Complete"

[Command6]
group = "Predefined6"
description = "Simple command description6"
command = "kubectl get pods -A --field-selector = status.phase = Running | grep -v Complete"

[Command7]
group = "Predefined7"
description = "Simple command description7"
command = """ kubectl get no -o json | \
              jq -r '.items | sort_by(.status.capacity.memory)[]|[.metadata.name,.status.capacity.memory]| @tsv' """

[Command8]
group = "Predefined8"
description = "Simple command description8"
command = """ kubectl get pods -A --field-selector = status.phase! = Running\
              | grep -v Complete \
              | grep -v Complete \
              | grep -v Complete \
              | grep -v Complete """

[Command9]
group = "Predefined9"
description = "Simple command description9"
command = "kubectl get pods -A --field-selector=status.phase!=Running | grep -v Complete"

[Command10]
group = "Predefined10"
description = "Simple command description10"
command = "kubectl get pods -A --field-selector = status.phase = Running | grep -v Complete"

[Command11]
group = "Predefined11"
description = "Simple command description11"
command = """ kubectl get no -o json | \
              jq -r '.items | sort_by(.status.capacity.memory)[]|[.metadata.name,.status.capacity.memory]| @tsv' """

[Command12]
group = "Predefined12"
description = "Simple command description12"
command = """ kubectl get pods -A --field-selector = status.phase! = Running\
              | grep -v Complete \
              | grep -v Complete \
              | grep -v Complete \
              | grep -v Complete """