# These are supported funding model platforms https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

github: JWebDev
ko_fi: kubehelper
liberapay: kube-helper
issuehunt: kube-helper
custom: [paypal.me/kubehelper]
