apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
  labels:
  {{- include "kubehelper.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: {{ .Values.rbac.rules.verbs | toJson | indent 4}}
  - nonResourceURLs: [ "*" ]
    verbs: {{ .Values.rbac.nonResourceURLs.verbs | toJson | indent 4}}