#ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-helper-sa
  namespace: default
  labels:
    app: kube-helper
    kubernetes.io/cluster-service: "true"
    ns: default
---

#Service
apiVersion: v1
kind: Service
metadata:
  name: kube-helper-svc
  namespace: defaule
  labels:
    app: kube-helper
    kubernetes.io/cluster-service: "true"
    ns: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kube-helper
    ns: default
---

#ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-helper-cr
  labels:
    app: kube-helper
    ns: default
rules:
  - apiGroups:
      - ""
    resources:
      - apiservices
      - bindings
      - clusterrolebindings
      - clusterroles
      - componentstatuses
      - configmaps
      - controllerrevisions
      - cronjobs
      - customresourcedefinitions
      - csidrivers
      - csinodes
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - ingressclasses
      - jobs
      - limitranges
      - localsubjectaccessreviews
      - mutatingwebhookconfigurations
      - namespaces
      - networkpolicies
      - nodes
      - pods
      - poddisruptionbudgets
      - podsecuritypolicies
      - podtemplates
      - persistentvolumes
      - persistentvolumeclaims
      - priorityclasses
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - rolebindings
      - roles
      - runtimeclasses
      - secrets
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - serviceaccounts
      - services
      - statefulsets
      - storageclasses
      - tokenreviews
      - validatingwebhookconfigurations
    verbs: [ "get","list" ]
  - nonResourceURLs: [ "*" ]
    verbs: [ "get","list" ]
---

#ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-helper-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  name: kube-helper-cr
subjects:
  - kind: ServiceAccount
    name: kube-helper-sa
    namespace: default
---

#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-helper
  namespace: default
  labels:
    app: kube-helper
    ns: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-helper
      ns: default
  template:
    metadata:
      labels:
        app: kube-helper
        ns: default
    spec:
      serviceAccountName: kube-helper-sa
      automountServiceAccountToken: true
      containers:
        - name: kube-helper
          image: docker.elastic.co/kibana/kibana-oss:6.2.4
          env:
            - name: KUBE_HELPER_UI_USERNAME
              value: kube
            - name: KUBE_HELPER_UI_PASSWORD
              value: helper
          ports:
            - containerPort: 8080
              name: ui
              protocol: TCP
