[git]
url = ""
user = ""
password = ""
branch = ""
email = ""

[[cron_job]]
name = "your_job-name"
isActive = false
expression = "*/20 * * * * *"
command = "kubectl get pods -A --field-selector = status.phase = Running | grep -v Complete"
shell = "bash"
description = "my always active cron job"

[[cron_job]]
name = "your_job-name2"
isActive = false
expression = " * */5 * * * *"
command = "kubectl get pods -A --field-selector = status.phase = Running | grep -v Complete"
shell = "bash"
description = "my always inactove cron job"
