# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/GithubDocker

on:
  workflow_dispatch:
    branches:
      - master
      - develop
    inputs:
      releaseTag:
        description: 'Docker Release Tag'
        required: true
        default: '1.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kubehelper/kubehelper/kubehelper
          tags: ${{ github.event.inputs.releaseTag }}
